name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: x64
          cache: 'pip'
      - name: Copiar Configurações .env
        run: |
          cp contrib/env-sample .env
      - name: Instalar dependências
        run: |
          #    pip install -r requirements-dev.txt
               pip install pipenv
               pipenv sync --dev
      - name: Rodar flake8
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3'
      - name: Rodar Testes Automáticos
        run: |
          pipenv run pytest . --cov=.
      - name: Relatório Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pipenv run codecov
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos