name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Copying configurations
        run: |
          cp contrib/env-sample .env
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev
      - name: Rodar flake8
        uses: py-actions/flake8@v1
        with:
          checkname: 'flake8_py3'
      - name: Rodar Testes Automáticos
        run: |
          pipenv run pytest . --cov=.

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3


